"""
25 major US cities with coordinates and NWS office grid info.
All cities are markets actively traded on Kalshi weather events.
"""

CITIES: dict[str, dict] = {
    "NYC": {
        "name": "New York City",
        "lat": 40.7128,
        "lon": -74.0060,
        "kalshi_series": "KXHIGHNY",
        "nws_office": "OKX",
        "nws_grid": (33, 37),
        "tz": "America/New_York",
    },
    "LAX": {
        "name": "Los Angeles",
        "lat": 34.0522,
        "lon": -118.2437,
        "kalshi_series": "KXHIGHLA",
        "nws_office": "LOX",
        "nws_grid": (149, 48),
        "tz": "America/Los_Angeles",
    },
    "CHI": {
        "name": "Chicago",
        "lat": 41.8781,
        "lon": -87.6298,
        "kalshi_series": "KXHIGHCHI",
        "nws_office": "LOT",
        "nws_grid": (74, 73),
        "tz": "America/Chicago",
    },
    "HOU": {
        "name": "Houston",
        "lat": 29.7604,
        "lon": -95.3698,
        "kalshi_series": "KXHIGHHOU",
        "nws_office": "HGX",
        "nws_grid": (66, 97),
        "tz": "America/Chicago",
    },
    "PHX": {
        "name": "Phoenix",
        "lat": 33.4484,
        "lon": -112.0740,
        "kalshi_series": "KXHIGHPHX",
        "nws_office": "PSR",
        "nws_grid": (155, 57),
        "tz": "America/Phoenix",
    },
    "PHL": {
        "name": "Philadelphia",
        "lat": 39.9526,
        "lon": -75.1652,
        "kalshi_series": "KXHIGHPHI",
        "nws_office": "PHI",
        "nws_grid": (49, 68),
        "tz": "America/New_York",
    },
    "SAN": {
        "name": "San Antonio",
        "lat": 29.4241,
        "lon": -98.4936,
        "kalshi_series": "KXHIGHSAT",
        "nws_office": "EWX",
        "nws_grid": (156, 90),
        "tz": "America/Chicago",
    },
    "SAN_DIEGO": {
        "name": "San Diego",
        "lat": 32.7157,
        "lon": -117.1611,
        "kalshi_series": "KXHIGHSD",
        "nws_office": "SGX",
        "nws_grid": (55, 15),
        "tz": "America/Los_Angeles",
    },
    "DAL": {
        "name": "Dallas",
        "lat": 32.7767,
        "lon": -96.7970,
        "kalshi_series": "KXHIGHDAL",
        "nws_office": "FWD",
        "nws_grid": (93, 84),
        "tz": "America/Chicago",
    },
    "SJC": {
        "name": "San Jose",
        "lat": 37.3382,
        "lon": -121.8863,
        "kalshi_series": "KXHIGHSJ",
        "nws_office": "MTR",
        "nws_grid": (96, 83),
        "tz": "America/Los_Angeles",
    },
    "ATX": {
        "name": "Austin",
        "lat": 30.2672,
        "lon": -97.7431,
        "kalshi_series": "KXHIGHAUST",
        "nws_office": "EWX",
        "nws_grid": (156, 100),
        "tz": "America/Chicago",
    },
    "JAX": {
        "name": "Jacksonville",
        "lat": 30.3322,
        "lon": -81.6557,
        "kalshi_series": "KXHIGHJAX",
        "nws_office": "JAX",
        "nws_grid": (73, 60),
        "tz": "America/New_York",
    },
    "FTW": {
        "name": "Fort Worth",
        "lat": 32.7555,
        "lon": -97.3308,
        "kalshi_series": "KXHIGHFTW",
        "nws_office": "FWD",
        "nws_grid": (88, 84),
        "tz": "America/Chicago",
    },
    "CLT": {
        "name": "Charlotte",
        "lat": 35.2271,
        "lon": -80.8431,
        "kalshi_series": "KXHIGHCLT",
        "nws_office": "GSP",
        "nws_grid": (61, 56),
        "tz": "America/New_York",
    },
    "IND": {
        "name": "Indianapolis",
        "lat": 39.7684,
        "lon": -86.1581,
        "kalshi_series": "KXHIGHIND",
        "nws_office": "IND",
        "nws_grid": (61, 59),
        "tz": "America/Indiana/Indianapolis",
    },
    "SFO": {
        "name": "San Francisco",
        "lat": 37.7749,
        "lon": -122.4194,
        "kalshi_series": "KXHIGHSF",
        "nws_office": "MTR",
        "nws_grid": (84, 105),
        "tz": "America/Los_Angeles",
    },
    "SEA": {
        "name": "Seattle",
        "lat": 47.6062,
        "lon": -122.3321,
        "kalshi_series": "KXHIGHSEA",
        "nws_office": "SEW",
        "nws_grid": (124, 67),
        "tz": "America/Los_Angeles",
    },
    "DEN": {
        "name": "Denver",
        "lat": 39.7392,
        "lon": -104.9903,
        "kalshi_series": "KXHIGHDEN",
        "nws_office": "BOU",
        "nws_grid": (57, 62),
        "tz": "America/Denver",
    },
    "BNA": {
        "name": "Nashville",
        "lat": 36.1627,
        "lon": -86.7816,
        "kalshi_series": "KXHIGHNAS",
        "nws_office": "OHX",
        "nws_grid": (43, 46),
        "tz": "America/Chicago",
    },
    "OKC": {
        "name": "Oklahoma City",
        "lat": 35.4676,
        "lon": -97.5164,
        "kalshi_series": "KXHIGHOKC",
        "nws_office": "OUN",
        "nws_grid": (74, 63),
        "tz": "America/Chicago",
    },
    "ELP": {
        "name": "El Paso",
        "lat": 31.7619,
        "lon": -106.4850,
        "kalshi_series": "KXHIGHELP",
        "nws_office": "EPZ",
        "nws_grid": (65, 43),
        "tz": "America/Denver",
    },
    "DCA": {
        "name": "Washington DC",
        "lat": 38.9072,
        "lon": -77.0369,
        "kalshi_series": "KXHIGHDCA",
        "nws_office": "LWX",
        "nws_grid": (95, 72),
        "tz": "America/New_York",
    },
    "LAS": {
        "name": "Las Vegas",
        "lat": 36.1699,
        "lon": -115.1398,
        "kalshi_series": "KXHIGHLV",
        "nws_office": "VEF",
        "nws_grid": (41, 25),
        "tz": "America/Los_Angeles",
    },
    "SDF": {
        "name": "Louisville",
        "lat": 38.2527,
        "lon": -85.7585,
        "kalshi_series": "KXHIGHLOU",
        "nws_office": "LMK",
        "nws_grid": (54, 55),
        "tz": "America/Kentucky/Louisville",
    },
    "MIA": {
        "name": "Miami",
        "lat": 25.7617,
        "lon": -80.1918,
        "kalshi_series": "KXHIGHMIA",
        "nws_office": "MFL",
        "nws_grid": (110, 37),
        "tz": "America/New_York",
    },
}
